- research/package.json
- research/src/components/layout.js
- research/yarn.lock
This PR adds syntax highlighting to code blocks:
Inline code tags still look good:
> feat: add syntax highlighting

- research/src/sources/spectrum. json5
I'll fill out all the components and implementation information if this data is a good start.
> Adding Spectrum

- research/src/components/select-anatomy.js
Creating a PR to change the default select anatomy per #26
> Update select anatomy default to button

- research/src/components/anatomy.js
- research/src/components/component-coverage.js
- research/src/pages/contribute.mdx
- research/src/utils/typography.js
> Link component source page to names

- research/src/pages/mission.research.mdx
Bo Cupp and I were reviewing the vision and he asked a good question if we had specific aspects we wanted to standardize on. As such, I added specific goals and non-goals which I think are worth agreeing on since the template has some of these sections but we should be sure to not duplicate other specs and end up being an [XKCD comic strip](https://xkcd.com/927/). I welcome any and all thoughts. @chrisdholt @levithomason @EisenbergEffect @dzearing @nicholasrice
> Specific low level goals for web specifications

- research/src/pages/mission.research.mdx
Added YAML front matter to specify page title when rendered to HTML.
> Add YAML front matter to specify page title when rendered to HTML

- research/src/pages/charter.research.mdx
- research/src/pages/mission.research.mdx
-----------------------
**NOTE:** This is not currently building for me, not entirely sure why but the `/sharp/` module keeps failing no matter what I try. That said I'd like folks to begin reviewing the charter content while I figure out why it won't build. I WILL NOT merge this PR until we ensure it won't break the build.
---------------------
This change adds a more in-depth charter of specific goals and process information for the group. @levithomason is working on a draft of the spec stages so I have not included those. Any feedback is welcomed.
For an easy to read version you can see it in rendered md here: https://github.com/WICG/open-ui/blob/gwhit-charter/research/src/pages/charter.research.mdx
> Charter initial draft

- research/src/pages/component-research-template.mdx
- research/src/pages/component-spec-template.mdx
- research/src/pages/contribute.mdx
This PR is trying to clarify the contribution process at request by @matthewp - so please take a glance and while working on a component please raise any questions you may have that I can further help clarify. 
@levithomason or @EisenbergEffect please review.
If you have time @chrisdholt can you take a glance as well.
> Adding contribution information

- research/src/components/layout.js
Page 404 there's no frontmatter what is breaking the build in master and the access to the custom 404 page.
> fix(layout): conditionally frontmatter access

- research/src/sources/bootstrap.json5
- research/src/sources/primer.json5
Updates Bootstrap and Primer to show the Flex component.
> Updating Bootstrap and Primer documentation to include their use of Flex

- research/src/pages/mission.research.mdx
Based on our discussion, I have created a PR that tries to provide clarity for Open UI.
> Clarified vision statement

- meetings/telecon/2020-06-18.md
- meetings/telecon/2020-07-02.md
Adding myself as an attendee for the past couple telcons, mostly for my own reference. Apologies, this is a bit goofy of a PR!
> Update historical attendee data

- research/src/components/component-coverage.js
- research/src/components/concept-coverage.js
- research/src/components/concept.js
- research/src/components/concepts.js
- research/src/sources/index.js
This PR allows to collapse sections from concepts page
> feat(concept): allow to collapse concepts sections

- .gitignore
That allow open project without seeing changes imposed by IDE/editor.
> Ignore folders with IDE configuration

- research/src/sources/atlassian.json5
- research/src/sources/evergreen.json5
> Remove not existing concepts from Atlassian and Evergreen

- research/README.md
Setting up the project again on a fresh WSL2 instance and thought the added detail here might be helpful to other contributors.
> Add some useful links and clarifying statements to research README

- research/src/sources/index.js
- research/src/sources/lion.json5
I've added the Lion components to the sources.
> Add Lion to sources

- research/src/pages/mission.research.mdx
> Fix contact link

- research/src/components/specimens.js
- Remove reduntant for assistive technology `An image of the`
I decide do not change `on a` to `of a` since this is more about formal nature of the wording.
See #208
> Improve alt text

- research/src/pages/charter.research.mdx
- research/src/pages/contribute.mdx
- research/src/pages/slider.research.parts.mdx
- research/src/pages/table.proposal.mdx
- s/WIA-ARIA/WAI-ARIA
- s/WICAG/WCAG
> docs: fix typos

- research/src/components/anatomy-components.js
- research/src/components/anatomy.css
- research/src/components/checkbox-anatomy.js
- research/src/components/file-anatomy.js
- research/src/components/select-anatomy.js
This PR updates anatomies to use React components, and resolves console errors around components and classnames.
> Resolve React console errors

- meetings/telecon/2021-02-25.md
minutes generated post hoc from irc log
> add link to minutes

- research/src/pages/file/file.proposal.mdx
This PR updates the tabbing behaviour of `openui-file`, as per the resolution in #107.
> Update file input tab behaviour

- research/src/pages/documentation/get-involved.mdx
closes: https://github.com/openui/open-ui/issues/304
> [Navigation Architecture] Elevate mechanical participation information on Get Involved

- research/src/pages/popup/popup.proposal.mdx
The behavior described in #369 is already in the spec, but needs a note to clarify for authors.
> [Popup] Add note about delegatesfocus/autofocus conflict resolution (fixes #369)

- research/src/pages/checkbox/checkbox.research.findings.mdx
Add checkbox research. In this research, I surveyed the top 100 brands from [Interbrand](https://www.interbrand.com/best-global-brands/). I spent about 5-10 minutes for each brand, looking across their site, and finding a checkbox implementation. I assessed each checkbox implementation in 3 areas, as outlined in the research. The data is intentionally anonymized.
> Add checkbox research

- meetings/telecon/2022-04-07.md
> Add minutes to telecon 2022-04-07

- meetings/telecon/2022-05-19.md
> pseudo-class fixes

- meetings/telecon/2022-07-07.md
editorial: markdown code for attribute mentions
> editorial: code for attrs

- research/src/pages/popup/popup.research.explainer.mdx
This PR does some light general cleanup, but mainly updates the animation behavior with the resolutions from https://github.com/openui/open-ui/issues/335#issuecomment-1178038555.
> Update events and animation behavior, plus cleanup

- meetings/telecon/2022-07-28.md
code/angle brackets around option to clarify it’s an element
> editorial: <option> is an element

- meetings/telecon/08-25-22.md
editorial, add code markup to attribute and element names
> editorial: code markup

- meetings/telecon/2022-08-11.md
markup 'selected' attribute and option element as code
> editorial: code 'selected' attr, option element

- README.md
We have our own CG, replacing some out of date mentions/links to WICG with Open UI CG
> replace WICG ref with Open UI CG

- research/src/pages/popup/popup.research.explainer.mdx
This is just a quick grammar fix.
> Change "confer to" to "confer upon"

- research/src/pages/popup/popup.proposal.alternatives.mdx
It was [mentioned](https://github.com/whatwg/html/issues/7785#issuecomment-1272334050) that this CSSWG issue was helpful, so this adds a direct link.
> Add link to CSSWG 6965

- research/src/pages/mission.research.mdx
I got some feedback that it would be good to update the home page content a bit and so I've made these minor changes. There are probably some larger changes that should occur based on our past 2 years of effort to reflect the reality of this CG but for now we'll stick to these minor adjustments.
> Adjusted home page content

- research/src/sources/carbon.json
This PR fixes the wording of `paginaiton`
> chore: fix wording of `paginaiton`

- site/src/pages/components/selectmenu.mdx
This was discussed in https://github.com/openui/open-ui/issues/547
> Add :open/:closed to selectmenu explainer

- site/src/pages/components/popover.research.explainer.mdx
Adding an extra article I created about Open UI and the Popover API
link: https://utilitybend.com/blog/open-ui-and-the-popover-api
> [Popover explainer] Add article "Open UI and the Popover API" in the link section

- site/src/pages/components/file.mdx
- site/src/pages/components/table.mdx
> Add missing ;

- site/src/pages/components/accordion.research.mdx
- site/src/pages/components/disclosure.research.mdx
- site/src/sources/kolibri.json
- site/src/sources/lightning.json
- site/src/sources/lion.json
- site/src/sources/web.json
This adds stub-ish research pages for the accordion and disclosure components.
> Add (stub-ish) research pages for accordion and disclosure.

- site/src/pages/components/accordion.explainer.mdx
Also, link to proposal for details styling.
> Update Exclusive Accordion explainer based on discussion in April 27 meeting.

- .github/CODEOWNERS
> Update CODEOWNERS to add @dbaron

- site/src/pages/components/accordion.explainer.mdx
These alternatives were discussed in yesterday's teleconference.
Also, link to document describing issues with CSS Toggles.
> Describe other alernatives to this proposal.

- site/src/pages/components/accordion.explainer.mdx
Merge the sections on panelset and spicy sections based on the discussion starting at
https://github.com/openui/open-ui/pull/746#issuecomment-1540494785
> [exclusive-accordions] Merge sections on panelset and spicy sections.

- site/src/pages/components/accordion.explainer.mdx
These solutions represent what I'm currently planning to prototype.
> [exclusive-accordion] Propose solutions to most open issues.

- site/src/pages/components/accordion.explainer.mdx
- site/src/pages/components/accordion.research.mdx
Addresses part of #752 and some related issues.
> [exclusive-accordion] Discuss accordions that have exactly one item open

- site/src/pages/components/accordion.research.mdx
> [accordion.research] Categorize Semantic UI correctly, and note defaults

- site/src/pages/components/accordion.research.mdx
I read the Material UI documentation more carefully this time.
This fixes the remainder of #751.
> [accordion.research] Fix classification of Material UI.

- .gitignore
- site/src/pages/components/accordion.explainer.mdx
- site/src/pages/components/popover.research.explainer.mdx
- site/src/pages/components/popup.proposal.alternatives.mdx
I noticed this was inconsistent across the site so this PR should fix that.
I've also added .idea to the gitignore for contributors (like me) who use JetBrains IDEs.
> Correct instances of Javascript to JavaScript

- site/src/pages/get-involved.mdx
Fixed some grammatical errors I spotted and also fix capitalisation of GitHub
> Fix some typos in get-involved

- README.md
minor punct fix, replace --- with — emdash as that looks like what was intended
> replace --- with emdash

- site/src/pages/components/selectmenu.mdx
fixes https://github.com/openui/open-ui/issues/705
> Add form semantics section

- meetings/telecon/chair-meeting.md
- meetings/telecon/meetings.md
this is to try and address #789
> Improve scribe docs (re #789)

- site/src/pages/components/selectlist.mdx
Fixes https://github.com/openui/open-ui/issues/153
> Add note about size to selectlist

- site/src/sources/chromium.json
Initial work to add full specs of Chromium components
Part of #840
> Copy components from web to Chromium design system

- site/src/sources/firefox.json
- site/src/sources/index.js
This is just an initial PR to get the JSON file in place. Having copied web.json as a base. I will do follow ups to add in specifics of concepts and eventually screenshots
Part of #840
> Add initial firefox design system

- site/src/pages/components/selectlist.mdx
> Add definition for showPicker method to the selectlist explainer

- site/src/pages/components/invokers.explainer.mdx
This ports the Invokers explainer from https://github.com/keithamus/invoker-buttons-proposal/ to here.
Refs https://github.com/keithamus/invoker-buttons-proposal/issues/29
/cc @mfreed7
> add invokers explainer

- site/src/pages/components/invokers.explainer.mdx
> fix typo in invokers explainer

- site/src/components/checkbox-anatomy.jsx
- site/src/components/file-anatomy.jsx
- site/src/pages/components/file.mdx
Also fix file structure to use a button and a span element
Fixes #743
> Correct ordering of part and slots in file and checkbox anatomy

- site/package.json
- site/src/components/anatomy.jsx
- site/src/components/component-coverage.jsx
- site/src/components/component-name-matrix.jsx
- site/src/components/concept-coverage.jsx
- site/src/components/concepts.jsx
- site/src/components/design-systems-list.jsx
- site/src/components/navigation/navigation.astro
- site/src/sources/index.js
- site/yarn.lock
This PR removes lodash from the site.
Most of what it's doing can be trivially replaced by vanilla JS.
> Remove lodash

- site/src/pages/components/invokers.explainer.mdx
Remove auto action
Closes #911
> Update invokeaction defaults for select and input

- site/package.json
- site/src/components/community-links.css
- site/src/components/community-links.jsx
- site/yarn.lock
> Add X to the community links

- site/src/pages/components/selectlist.mdx
Fixes https://github.com/openui/open-ui/issues/742
> Add note about selection follows focus

- site/src/components/select-anatomy.jsx
Update selectlist anatomy
- Change selectedvalue to selectedoption
- Add marker part
- Add optional legend part
> Update selectlist anatomy

- site/src/pages/components/invokers.explainer.mdx
> Change mute invoke action to toggleMuted

- site/src/components/select-anatomy.jsx
Quick fix for consistency after the recent rename--caught while reading through. :)
> Consistency: update to <button type=select>

- site/src/pages/components/selectlist.mdx
This follow the resolution in
https://github.com/openui/open-ui/issues/977
> Add size and multiple to select explainer

- site/src/pages/components/focusgroup.explainer.mdx
> Add logical property support to proposed focus-group-direction

- .github/CODEOWNERS
I realised where I went wrong the time before....
> Fix mistake in code owners

- site/src/pages/components/interest-invokers.explainer.mdx
To show that submit buttons and area elements are supported
> Update interest invokers introduction

- site/src/pages/components/invokers.explainer.mdx
Also fix missing usages of button value for returnValue of dialog.
> Fix dialog toggle action in invokers

- site/src/pages/components/interest-invokers.explainer.mdx
- site/src/pages/components/invokers.explainer.mdx
> Add `interestaction` to interest invokers.

- site/src/pages/components/interest-invokers.explainer.mdx
Edits from https://github.com/openui/open-ui/issues/1032
> Add SVGAElement to InterestInvokerElement includes list

- site/src/pages/components/selectlist.mdx
Fixes https://github.com/openui/open-ui/issues/571
Fixes https://github.com/openui/open-ui/issues/825
> Add selectedoption section to select explainer

- site/src/pages/components/selectlist.mdx
I got feedback that this sentence was confusing since it makes it sound like the selectedoption element doesn't clone rich content.
> correct sentence about selectedoption

- site/src/pages/get-involved.mdx
Also add links to the html and csswg issue trackers.
> Remove Simon from get-involved

- site/src/pages/components/selectlist.mdx
This was resolved here:
https://github.com/openui/open-ui/issues/1063#issuecomment-2195407344
> Add selectedoptionelement attribute to select explainer

- site/src/pages/components/customizableselect.mdx
This patch adds the UA stylesheet for customizable select to the customizable select explainer
> add ua stylesheet

- site/src/sources/kolibri.json
> docs: upgrade public-ui kolibri spec

- site/src/pages/components/switch.explainer.mdx
After resolving to not add a toggle method in https://github.com/openui/open-ui/issues/1046 the question is answered and no further edits are necessary.
> chore(switch): remove toggle question after resolution

- site/src/pages/components/customizableselect.mdx
Fixes https://github.com/openui/open-ui/issues/825
> Don't observe mutations in <selectedoption>

- site/src/pages/components/customizableselect.mdx
Based on https://github.com/openui/open-ui/issues/1112
I thought i'd update this page already. I checked this with @josepharhar first. Let me know if I missed something.
> [Customizable select] Rename selectedoption to selectedcontent

- site/src/pages/components/invokers.explainer.mdx
> Add 'request-close' command for dialogs

- site/src/pages/components/interest-invokers.explainer.mdx
See the new text, but this adds a pseudo class for the "has interest" state.
> Add the `:has-interest` pseudo class

- site/src/pages/components/customizableselect.mdx
I'm likely going to be changing these links in the coming weeks due to API changes, and I thought this part of the explainer would act as a good permanent link to demos
> Update select demos links

- site/src/pages/components/interest-invokers.explainer.mdx
See discussion here:
https://github.com/openui/open-ui/issues/1133#issuecomment-2672751043
> Revamp the keyboard section with the results of recent discussion

- site/src/pages/components/interest-invokers.explainer.mdx
See https://github.com/openui/open-ui/issues/1133#issuecomment-2689101970
> Incorporate recent discussion about `interesttarget` keyboard behavior

- .github/CODEOWNERS
- site/src/pages/components/enhanced-range-input.explainer.mdx
Forgot to add myself as author, noticed that this is in other explainers as well.
> [Enhanced Range Input] Add author to range input

- site/src/pages/components/menu.explainer.mdx
Add a reading list of links shared about menu.
> [menu] Add a reading list with links

- site/src/pages/components/interest-invokers.explainer.mdx
This was brought up by the TAG, so I'm adding some details.
> Add speculation rules section to interesttarget

- site/src/pages/components/menu.explainer.mdx
> [menu]: Support default/initial checkedness

- site/src/pages/components/interest-invokers.explainer.mdx
See this discussion:
https://github.com/whatwg/html/issues/11312
> Rename `interesttarget` to `interestfor`

- site/src/pages/components/interest-invokers.explainer.mdx
I'm not sure if the curly braces were supposed to do something interesting, but they are causing a build failure.
> Remove curly braces around note

- site/src/pages/components/openable.explainer.mdx
Built atop #1223 
Closes https://github.com/openui/open-ui/issues/1158
> [Openable] focus management updates

- site/src/pages/components/interest-invokers.explainer.mdx
...to make it clear which options were picked
> Update interest invokers explainer 

- site/src/components/select-anatomy.jsx
- site/src/pages/components/customizableselect.mdx
A lot has changed since much of this text was written, including the launching of the feature and some API changes.
Fixes https://github.com/openui/open-ui/issues/1154
> Update customizable select explainer
