README.md

Add link to WICG thread.
Also, in https://github.com/tkent-google/std-switch the `<toggle>` is currently named `<std-switch>` so I changed it to align with that document.

Add link to WICG thread.

---

research/gatsby-config.js
research/package.json

This updates the github links in the live docs to point to this repo, instead of the Stardust repo.
👍

docs: update urls to WICG repo

---

research/src/pages/switch.mdx
research/src/pages/switch.research.mdx

This is just a cleanup PR.  We needed at least one page with a `researchFor` front matter entry in order for the build to be happy.  Now that we have a real research page (`select`), we no longer need this stub page.

Remove empty switch page

---

research/src/components/concepts.js
research/src/components/layout.js
research/src/components/specimens.js
research/src/sources/index.js

Fixes #40 
This PR fixes image alt tags.  In order to do this, the function for returning images was updated to include the design data.  We now have nice alt tags and images grouped by design system.

Improve image alt tags and specimens

---

research/src/sources/index.js
research/src/sources/web.json5

Currently the component matrix contains the content for WIA-ARIA but these are not a 1:1 with the actual controls that ship with the browser. As such I'm adding in a web platform section that has the majority of our controls. I did not add in JS invoked controls, merely the HTML ones. I figured most of the JS ones are covered by WIA-ARIA.

Added the web platform specific controls

---

.github/CODEOWNERS

This is a simple change based on our resolution for adding editors.
This is to add editors for select and the spec template of @EisenbergEffect in addition to Levi and Myself.
I need approval from you @levithomason and it would be good to ensure that you want this responsibility @EisenbergEffect :)

Adding initial editors for select & template

---

research/src/components/concepts.js
research/src/sources/semantic.json5

This PR fixes a build break caused by an instance of `<ConceptCoverage>` in concepts.js where the conceptOpenUIName was being passed to the conceptName parameter.  This resulted in a failed lookup when we try to search the concept framework-specific names for the openUIName.  The fix is to pass the uniqueName to the parameter instead.
This was triggered by Semantic's Select's minCharacters which has an openUIName that is not present anywhere else, with the result that we went down the buggy codepath.

Fix build break from wrong param passed to <ConceptCoverage>

---

research/src/components/navigation.js
research/src/pages/contribute.mdx
research/src/pages/mission.research.mdx

I've updated the contribution document again. This time adding a terrible subnav at the top of the document but will hopefully allow people to jump down a bit quicker. Added in some anchors for sharing. Also added in some definitions for use across documents. The definition of a control is the important aspect as that is what is outlined in each of our specs as top level sections.
Also forced Home to be the first nav item.
This resolves #81

Added definitions to contribute

---

research/src/components/image.js

Use the standard srcset instead.

image: Don't use the non-standard zoom property to shrink images.

---

research/src/components/anatomy.css
research/src/components/select-anatomy.js
research/src/components/specimens.js
research/src/styles/spec.css

This PR does the following and will resolve #80 
I have added tentative names for the slots that are outside of the defined parts. While working on the checkbox @nicholasrice brought up a valid question of why we would want to allow the author to completely replace an entire part. This is to ensure that we aren't locking in current anatomies and behaviors completely. This would allow authors to replace the light DOM with their own variation of part. For example:
```
<select>
<div slot="button-wrapper">
<p>I'm able to put whatever I want in here, no limitations</p>
<div part="button">This is the button that will trigger the open state of the <select>
</div>
<div part="list-box">
... options ...
</div>
</select>
```
This will allow our controller code that knows to look for the button part …

Updated anatomy with named outer slots

---

components/src/select/demos/bootstrap-split/index.html
components/src/select/select.template.ts
components/src/select/select.ts

FAST-Element currently declaratively binds event listeners with the capture option set to true. For this example, the event listener must fire during the bubble phase to work intuitively. This change adjusts the listener to fire during the bubble phase.

fix: wires select's click handler using imperative syntax

---

research/src/components/image.js

property `srcset` throws console error since the expected property is `srcSet`

fix(image): fix property typo

---

research/src/components/component-name-matrix.js

Components whose names ended with "e" or "er" where not grouped together with their plural counterpants because of an error in the regex. This PR fixes that issue.
__Before:__
__After:__

Fixing component name matrix regex to correctly group items that end with 'e' or 'er'

---

research/src/components/component-name-matrix.js

- fixes: #23 
Handle big names in the components matrix by using ellipsis as overflow and title for hover name:

fix(ComponentsMatrix): fix large names display

---

meetings/telecon/meetings.md

added dates & links to May-July agendas, couldn't find immediate minutes but at least linking to the planned agendas seems like a good idea. and the CSSWG + Open UI meeting happening today.

+meetings May-Aug

---

research/src/pages/select/select.proposal.mdx
research/src/styles/spec.css

Add typeahead behavior to the `<select>` anatomy.
This behavior allows a user to choose items in the listbox by typing characters that match the first letters of a given `<option>`.  After a short timeout, the search "buffer" is cleared, and the user can begin a new search.
This is distinct from the "filtering" approach associated with comboboxes that have a textbox and listbox, which we haven't yet included in the anatomy.  See discussion in #104 and  #145.
Closes #145.

Add typeahead algorithm for <select>

---

research/src/pages/select/select.proposal.mdx

Create a new section to define "light dismiss" behavior for the `<select>` listbox part, and reference the new section from the Open State Section.
Ideally we would describe this behavior in terms of a `blur` or `focusout` event, but it turns out that both of these are not adequate for the task; see #137.  To achieve this behavior today would require a combination of multiple JS events to prevent the listbox from collapsing when non-focusable content inside the listbox is clicked.  In the future we could consider fleshing out the light dismiss section to clearly specify this combination, or reference a new platform primitive if one is introduced to make this easier.
Closes #137 .

Create section defining 'light dismiss' behavior of `<select>` listbox part

---

research/src/components/navigation.js
research/src/pages/checkbox.proposal.mdx
research/src/pages/checkbox.research.mdx
research/src/pages/contribute.mdx
research/src/pages/select/select.proposal.mdx
research/src/pages/select/select.research.mdx
research/src/pages/table.proposal.mdx
research/src/pages/table.research.mdx

In this change I am adjusting the nav to allow for hidden proposals and analysis to continue to reside under the category rather than removing it when a path-to-proposal is added. This was highlighted by the PR #183 as I'd like to have the link to the skeleton proposal still work. I like this idea as well as the author may want to get the proposal to a certain place before actually proposing it but this will allow the proposal to be worked on without actually being surfaced before their ready to request an Editor's Draft.

Changed the heading of components to proposals to reflect what they are

---

research/src/pages/tabs.proposal.mdx
research/src/pages/tabs.research.mdx

These are just skeletons and not filled out. Intend to iterate on these a little at a time.

Add tabs proposal and research skeleton docs

---

research/gatsby-config.js
research/package.json
research/src/components/logo.js
research/src/utils/typography.js
research/yarn.lock

Use a Gatsby plugin to improve the initial load of font awesome icons. This plugin inlines the FontAwesome CSS in the `head` of the HTML pages so that when the SVGs are rendered they are properly styled and sized on initial render.
Before (gif that loops twice then stops):
After (gif loops 2x):
Also:
* Specify a width for the OpenUI logo image to avoid the OpenUI text jumping once the logo image loads
* Specify similar fallback typefaces for our body font. "Source Sans Pro" is a sans-serif font while the original fallbacks were serif fonts. I've adjusted the fallbacks to also be sans-serif fonts so the shift in typeface (once Source Sans Pro loads from Google Fonts) is a little less dramatic
* Add yarn scripts for `gatsby clean` and `gatsby serve`. I often use these to test my changes on …

Improve initial load of FontAwesome icons

---

research/src/pages/select/select.proposal.mdx

Per the [resolution](https://www.w3.org/2020/12/03-openui-minutes.html#resolution01) from the 3 December 2020 meeting, clarify that the `open` state will be author-visible and author-changeable by both a JS property and an HTML content attribute.  This resolves #229 since that allows authors to make a `<select>` open by default.
Additionally:
- Fix the formatting/wording of the "Default State" section, which formerly had the misleading top-level bullet "The state of the `<select>` is set to `open`".
- Update the heading of the table in the "`<select>` Properties" section to agree with the section name.
Longer term we should consider formalizing which of the properties are reflected as HTML content attributes.  Right now there isn't really anything specifying that normatively.

Clarify that open state can be set to get default-opened behavior

---

research/package.json
research/src/components/community-links.js
research/src/components/global.css
research/src/components/header.js
research/src/components/layout.js
research/src/components/navigation.js
research/yarn.lock

On screens up to 640px wide, the site navigation is moved into a menu that is toggled on click. For this PR, I wanted to keep it very simple to serve as a stop-gap (as suggested in #170) until the proposed re-design in #29 happens.
Some current limitations I'll tackle in future PRs
* The select & checkbox proposal pages as well as the component name matrix page have tables that overflow the page on small screens. I'll investigate making this mobile friendly later.
* The mobile menu isn't interactive until our JS loads which is currently a 1.2 MB (😱) minified gzipped file. I imagine on a phone with a spotty connection it may take some time to load. In another PR I'll investigate reducing this bundle size so the mobile menu can become interactive faster.
I'll add some additional context to …

Move site nav into a menu on smaller screens

---

meetings/telecon/chair-meeting.md
meetings/telecon/meetings.md

This PR makes some slight tweaks to `meetings.md`. It:
- Communicates the cadence, day, and time of meetings.
- Links to the Discord server and explains relevant channels and onboarding etiquette.
- Describes how to join IRC and links to help for those who may be less familiar with the service.
- Lists commonly-used IRC commands and why they're used.
- Outlines the expected format for note-taking.
For ease of future maintenance I have also removed the list of meeting notes and linked to `telecon/` instead.

Remove meeting list, add info on how to join and how to participate

---

research/src/pages/tabs.research.mdx
research/src/pages/tabs.research.parts.mdx

Adding initial tabs research modeled in part after slider research model/link up and based on shared work we did during gathering in a gdoc.
Note that this uses images currently loaded from https://lh4.googleusercontent.com/ and I'm sure we'll have to fix that but given the troubles I've had I thought that having a WIP: PR where perhaps people could give more specific help/advice on sorting that out would be more efficient.

WIP: Add initial tabs research

---

research/src/pages/popup/popup.research.explainer.mdx
research/src/pages/popup/popup.research.mdx

The purpose of this PR is to quickly port over the [popup proposal from Microsoft Edge explainers](https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/main/Popup/explainer.md) to Open UI for standards incubation. This is based on a recent group resolution to take up `<popup>` and related APIs as an "official" work item.
This PR creates:
* A very small research index for popup. This will later be supplemented with content from #205 (smaller scope of transient-UI types than that current PR)
* A copy of the original popup explainer, in Open UI research directories.
I'm current hot-linking to images from the original explainer as I think the project needs a way to deal with/host images that are not part of the "Concepts" grids.

Port over popup explainer to Open UI for incubation

---

research/src/pages/documentation/design-system-analysis-guide.mdx

Two updates: 
* two headings were marked up with `<p>` and `<strong>`, replaced those by `hx` elements
* tweaked hierarchy so that there's only one `h1`, and “Adding a design system” and “Creating a component spec” are on the same level

Tweak heading hierarchy for ”Design Systems Analysis” page

---

research/src/pages/contribute.js
research/src/pages/documentation/get-involved.mdx
research/src/pages/documentation/working-mode.mdx

Closes: https://github.com/openui/open-ui/issues/303
- rename contribute to get started
- add redirect from contribute url
There only seemed to be one link to `contribute` from within the site. Are there any other external links I need to update? I've added a redirect regardless

[Navigation Architecture] Rename "Contribute" to "Get Involved"

---

research/src/pages/tabs.research.markup.mdx

- applies prettier to the document.
- fixes closing `tabbox` element with `tabset`.
- fixes closing `section` element with `tab`.
- fixes `gtml` code block with `html`.
- adds colon consistently after Pros/Cons/Recommendation list items.
- replaces apostrophe entity with apostrophe character.
- normalizes all html markup examples.
---
<a href="https://deploy-preview-353--open-ui.netlify.app/components/tabs.research.markup">Preview</a> | <a href="https://open-ui.org/components/tabs.research.markup">Current</a>

Update Tabs Markup Research

---

research/gatsby-config.js
research/package.json
research/yarn.lock

Uses `gatsby-plugin-sitemap` to generate the site's sitemap. 
closes: https://github.com/openui/open-ui/issues/314
The documentation for the plugin is [here](https://www.gatsbyjs.com/plugins/gatsby-plugin-sitemap) incase we want to use some of the non-default parameters. But the defaults seem sensible enough. 
It's worth noting that the 404 page is excluded by default. Are there any other pages we'd want to exclude?
You can test this yourselves by running gatsby build, and then opening the generated `sitemap.xml` in the public folder.

[Navigation Architecture] Create a site map page for the Open UI site

---

meetings/telecon/meetings.md

The discord invite URI gave me  an "expired" error so I've updated it to that given in the website which works (at least for now).

Fix discord invite

---

research/src/components/navigation.js

Fixes https://github.com/openui/open-ui/issues/377
- increases contrast of headings in navigation
- makes those headings bold, because with the smaller contrast there was too little difference with the links under the heading
- uses `h3` elements for the headings so that screenreader users can quickly jump to them with “navigate by heading”
- turns some of the `li`'s into `div`s so that the nesting is according to spec

Fix navigation contrast and improve markup

---

research/src/pages/popup/popup.proposal.mdx

What it says on the tin. `Should`s have normative meaning!

[Popup] Remove some stray shoulds from the editor's draft spec

---

research/src/pages/popup/popup.proposal.mdx

We decided via telecon discussion on #359:
> RESOLVED: preserve the behavior where when a user places focus into a text-entry-oriented control that has the popup attribute, the related popup will be shown. The platform will not provide a primitive to suppress this default behavior.
This change removes the related open question from the spec. No other changes should be needed to uphold the resolution

Remove comment about surpressing popup on focus (fixes #359)

---

research/src/pages/checkbox/checkbox.proposal.mdx
research/src/pages/select/select.proposal.mdx

Noticed some minor typos in the checkbox and select proposals, so this fixes them.

Fix typos in Checkbox and Select proposals

---

research/src/pages/documentation/working-mode.mdx

* typo: change "an stable" to "a stable".
* add periods to sentences in list items, where other sibling list items sentences ended with periods.

small editorial updates

---

research/src/pages/select/select.proposal.mdx

the current link was linking to https://atlaskit.atlassian.com/packages/design-system/select
the proposal changes link to https://atlassian.design/components/select/

change link URL to atlassian.design instead of old domain

---

meetings/telecon/2022-03-17.md

This adds an agenda for 2022-03-17 to the telecon, following the [instructions to setup a meeting](https://github.com/openui/open-ui/blob/main/meetings/telecon/chair-meeting.md#how-to-setup-a-meeting).
[Preview](https://github.com/jonathantneal/open-ui/blob/agenda/2022-03-17/meetings/telecon/2022-03-17.md)

Create Agenda for 2022-03-17

---

.github/workflows/stale.yml

The default limit is 30, which prevents the GitHub action from making its way through to the older tickets

Increase "stale" actions operations per run

---

research/src/pages/popup/popup.research.explainer.mdx

This just includes more references to the close signal proposal, and adds a bit more about "clicking outside".

Add more clarification around "click outside" and "close signal"

---

research/src/pages/popup/popup.research.explainer.mdx

This PR has two changes:
1. Replace `visibility:hidden` with `display:none` everywhere, per [this comment](https://github.com/openui/open-ui/issues/492#issuecomment-1077934691).
2. Add a section with an IDL reflected property, for general use plus feature detection.

Replace visibility with display, and add IDL property

---

research/src/pages/popup/popup.research.explainer.mdx

This PR fixes the text around the ordering of `initiallyopen`, stating that only the **first** popup will be shown, rather than the last. See [this comment](https://github.com/openui/open-ui/issues/494#issuecomment-1081256441).
This also removes a stale paragraph that I think used to be related.

Fix initiallyopen ordering text

---

meetings/telecon/meetings.md

Aparently, by following the advice in this documentation, I got off when the US switched to daylight savings time. The meeting is in fact, not 1900 UTC, but 1800 UTC (during US DST).
This version of the fix moves the anchor time zone to US Pacific time  
This [alternative PR](https://github.com/openui/open-ui/pull/509) fixes this by adjusting the time back by one hour UTC. Please choose one :)

Why I am late to this meeting (version 2)

---

research/src/pages/popup/popup.research.explainer.mdx

This PR also revamps the explainer significantly, changing the language from "proposal" to "explainer". Many details are also added, such as what "light dismiss" really means, the "nearest open ancestral popup" algorithm, and many more details. I also added links back to many of the recent resolutions where some of these decisions made.
I'm sure there are typos and issues here, but I did a first editing pass. Comments appreciated.

Update Popup explainer to incorporate all recent changes

---

research/src/pages/popup/popup.research.explainer.mdx

This updates the explainer for a number of recent resolutions, including these:
- [Rename `popup=popup` to `popup=auto`](https://github.com/openui/open-ui/issues/491)
- [Naming of the `:top-layer` pseudo class](https://github.com/openui/open-ui/issues/470)
- [Support for "boolean-like" behavior for `popup` attribute](https://github.com/openui/open-ui/issues/533)
- [Returning focus to previously-focused element](https://github.com/openui/open-ui/issues/327)
- [The `show` and `hide` events should not be cancelable](https://github.com/openui/open-ui/issues/321)
- [Remove `delegatesfocus`](https://github.com/openui/open-ui/issues/368)

Update explainer with recent resolutions

---

research/src/pages/prototypes/selectmenu.mdx

Per https://chromium-review.googlesource.com/c/chromium/src/+/3668816 the popup attribute syntax is changing.
It used to require `popup="popup"`. It has been renamed to `popup="auto"` and also now supports the boolean-like behavior so `popup` just works.
This PR changes the `selectmenu` usage docs to match this.

Changing popup="popup" to popup in the selectmenu usage docs

---

research/src/pages/focusgroup/focusgroup.explainer.mdx

* use of semantic elements where custom elements aren't really important for understanding
* ensure ARIA roles are present for custom elements for better clarity
* fix nested menuitems (Example 11), see https://github.com/w3ctag/design-reviews/issues/732#issuecomment-1159814503
* Consistency pass for elipses use

Accessibility pass over focusgroup examples

---

research/src/pages/popup/popup.research.explainer.mdx

Primarily this involves renaming "popup" to either "popUp" (for code) or "pop-up" (for prose). This PR also includes renaming `popup=async` to `popup=manual`, and some additions of issue links.

Update pop-up explainer to reflect recent resolutions

---

research/src/pages/focusgroup/focusgroup.explainer.mdx

follow on a11y updates per #550
- Minor consistency nits (wrapping inline-code snippets in code elements. definitely did not get all of them though)
- Update link to APG per its migration to a new website and revise the name to match its official title.
- Change "tabs and tabsets" to "tab widgets"
- added "or can benefit from" to sentence mentioning arrow key and other non-tab navigations - specifically because accordions and carousels do not necessarily "expect" arrow key or other mentioned key behaviors.
- Removed link for 'accessibility best practice' in the roving tabindex leadup paragraph - as it just linked to the APG homepage without any clear reason. Instead, added a direct link to a radiogroup example that employs the roving tabindex to the list of links that further demonstrate …

Further accessibility updates for focus group explainer

---

research/src/pages/popup/popup.research.explainer.mdx

Fixes a typo in the example code for a hint/tooltip in the pop up research

Fix hint example code in popup research

---

research/src/pages/popup/popup.research.explainer.mdx

This just incorporates the resolutions from #382 and #420:
- invoking attributes only work on buttons
- invoking attributes were renamed: `popuptoggletarget`, `popupshowtarget`, and `popuphidetarget`

[popup] Incorporate resolutions from #382 and #420

---

research/src/pages/popup/popup.research.explainer.mdx

The CSSWG [resolved](https://github.com/w3c/csswg-drafts/issues/7319#issuecomment-1225988203) to add an `:open` pseudo class, so this PR changes the pop-up behavior to use that instead of `:top-layer`.
Another [OpenUI issue](https://github.com/openui/open-ui/issues/561#issuecomment-1226017768) has decided to standardize the UA stylesheet, so this PR incorporates that into a new "Rendering" section.

Update pop-up explainer with CSS changes

---

research/src/pages/popup/popup.proposal-v1.mdx
research/src/pages/popup/popup.research.explainer.mdx

Quick set of two updates:
1. Add a link to the WHATWG html spec PR.
2. Remove a link to the obsolete discussion from the main menu.

Add link to spec PR, and remove old proposal from menu

---

meetings/telecon/2022-07-14.md

pseudo-class is a hyphenated word

- minor typo

---

research/src/pages/popup/popup.research.explainer.mdx

There have been more questions lately about why we're implementing this via a content attribute, and not, e.g. a `<popup>` element. For example, [here](https://github.com/w3ctag/design-reviews/issues/743#issuecomment-1233130208). This adds a section that goes into more detail. I also updated some links and the TOC.
@andrico1234 I could use help getting this landed soon, if possible. Thanks!
@scottaohara if you have time for a review, that'd be helpful!

Add motivation for attribute vs. element

---

research/src/pages/popup/popup.research.explainer.mdx

This explicitly adds the IDL (Javascript) attributes to the explainer for all of the existing content attributes. The `popUp`  IDL is already described in several sections.

Add IDL for all content attributes

---

research/src/pages/popup/popup.research.explainer.mdx

Per the [resolution](https://github.com/openui/open-ui/issues/617#issuecomment-1278015741), we have decided to punt `popup=hint` to the next version of this API. Accordingly, this PR removes `popup=hint` from the explainer.
While I was here, I also fixed a few bugs in the previously-outdated feature detection code.

Remove `popup=hint` from the explainer

---

research/src/pages/popup/popup.research.explainer.mdx

There was a remaining note that this section needed a better set of explanations. This PR adds that, while also correcting the specifics of the algorithm and fixing a few bugs.

Update Nearest Open Ancestral Pop-up section

---

research/src/pages/popup/popup.research.explainer.mdx

This follows the recent [OpenUI resolution](https://github.com/openui/open-ui/issues/627#issuecomment-1293918937) to rename the API.

Rename `popup` to `popover` globally

---

research/src/pages/popup/popup.research.explainer.mdx

Per the [resolution](https://github.com/openui/open-ui/issues/415#issuecomment-1285995113), changing focus is no longer a light dismiss trigger.

Remove `blur` as a light dismiss trigger

---

research/src/pages/popup/popup.research.explainer.mdx

The `popup` attribute used to live on `Element`, but as part of the spec review, it was moved to `HTMLElement`. As a result, the feature detection code needs to change.

Fix feature detection code

---

research/src/components/anatomy.css
research/src/components/select-anatomy.js
research/src/pages/prototypes/selectmenu.mdx
research/src/pages/select/select.proposal.mdx

This adds a `marker` part to the explainer and editor's draft as per our resolution to add a marker part https://github.com/openui/open-ui/issues/548#issuecomment-1262650219.
Also fixed the color contrast of the parts

Add `<marker>` part to anatomy and lists of parts

---

research/src/pages/popup/popup.research.explainer.mdx

Thought it might be good to start collecting some of the material being created around the API and have it listed here at the bottom.
Happy to change the formatting here to something that makes sense 😁

Add article links to explainer

---

research/src/pages/popup/popup.research.explainer.mdx

Remove lingering mention of `popover=hint` for now.

Remove lingering mention of popover=hint in the explainer

---

research/src/pages/popup/popup.research.explainer.mdx

The `popovertoggletarget`, `popovershowtarget` and `popoverhidetarget` attributes will initially map to `aria-expanded`.
This has already been implemented in Chromium browsers.  HTML AAM PR to add this mapping to the spec: https://github.com/w3c/html-aam/pull/446

Popover target attribute updates

---

research/src/pages/breadcrumb.proposal.mdx
research/src/pages/checkbox/checkbox.proposal.mdx
research/src/pages/file/file.proposal.mdx
research/src/pages/select/select.proposal.mdx
research/src/sources/index.js
research/src/sources/kolibri.json5

We have published a new full accessible web component library: https://public-ui.github.io/

docs: add kolibri accessible component lib

---

research/src/pages/components/popover.research.explainer.md

As part of the WHATWG spec landing process, several changes have recently been made to the Popover API:
1. The invoking attributes were changed significantly. The earlier three attributes were changed to two new attributes with different behaviors.
2. The animations behavior was not specified at all, and instead, new CSSWG issues are in progress to re-allow animations.
This PR updates the explainer accordingly.

Update popover explainer with recent changes

---

site/src/components/component-coverage.jsx
site/src/pages/components/alert.research.mdx
site/src/pages/components/avatar.research.mdx
site/src/pages/components/badge.research.mdx
site/src/pages/components/breadcrumb.research.mdx
site/src/pages/components/button.mdx
site/src/pages/components/card.research.mdx
site/src/pages/components/checkbox.research.concepts.mdx
site/src/pages/components/datepicker.research.mdx
site/src/pages/components/dialog.research.mdx
site/src/pages/components/file.research.mdx
site/src/pages/components/flex.research.mdx
site/src/pages/components/icon.research.mdx
site/src/pages/components/image.research.mdx
site/src/pages/components/menu.research.mdx
site/src/pages/components/select.research.mdx
site/src/pages/components/skeleton.research.mdx
site/src/pages/components/slider.research.mdx
site/src/pages/components/switch.mdx
site/src/pages/components/table.research.mdx
site/src/pages/components/tabs.research.mdx
site/src/pages/components/text.mdx
site/src/pages/components/toast.research.mdx
site/src/pages/components/tooltip.research.mdx

Move H2 header out of JSX component. Right now MDX does not apply rehype plugings over JSX content.
Fix #681

Fix displaying anchor links around Names

---

site/public/styles/global.css

Right now on the phones list markers is displayed partially outside of the screen and even may be invisible.

Make list markers visible on mobile

---

site/astro.config.js
site/public/styles/global.css
site/src/plugins/rehypeResponsiveTable.js

Without that change size of the page was jumping depends on the size of tables. Component Matrix is not affected by this change, and should be handled separately because of it's complexity

Make tables scroll on mobile

---

site/src/components/missing-images.jsx

I broke displayingn this list in #696
So I inspect other places where <li> is used,
and now finally everything seems fine

Fix list of missing images

---

site/public/styles/global.css

Somehow by default first line has small gap (or other lines does not have that padding) which make looking at large blocks of code unpleasant

Fix displaying code blocks

---

site/src/pages/components/selectmenu.mdx

This patch adds a table of contents and also:
- shuffles around some of the headings
- replaces "popup" with "popover"

Add table of contents to selectmenu explainer

---

site/src/layouts/ComponentLayout.astro

That fix looks like workaround but according to https://docs.astro.build/en/core-concepts/layouts/#nesting-layouts this is only way to pass parameters.

Fix displaying page titles in components

---

site/src/components/contributors.astro

When run automated checking of the website locally, astro constantly stop working. That's prevent `astro dev` from choking is github return broken response.

Improve stability when generating contributors

---

site/src/components/select-anatomy.jsx
site/src/pages/components/selectmenu.mdx

fixes https://github.com/openui/open-ui/issues/701

Update SelectAnatomy description of parts

---

site/astro.config.js
site/src/pages/component-spec-template.mdx
site/src/pages/components/breadcrumb.mdx
site/src/pages/components/popup.proposal-v1.mdx
site/src/pages/components/select.research.api.mdx
site/src/pages/components/tabs.mdx
site/src/pages/components/tabs.research.markup.mdx
site/src/pages/design-system-analysis-guide.mdx
site/src/pages/proposal-guide.mdx
site/src/styles/research.css

This fix bunch of issues on website
How I do it? I run awesome [Pa11y](https://github.com/pa11y).
I use `pa11y-ci --sitemap https://open-ui.org/sitemap-index.xml` to discover issues on prod. And then locally use `pa11y-ci --sitemap https://open-ui.org/sitemap-index.xml --sitemap-find https://open-ui.org --sitemap-replace http://localhost:3000` to validate my work.
- `/component-spec-template` has invalid header due to missing front matter.  I exclude this page from sitemap, since seems to be website do not mention that page anywhere.
- make `false` class more contrast. It was slightly less contrast then recommendation. Just use what tool suggests.
- Remove bunch of empty A tags. After introduction of rehypeHeadings plugin this manual thing not needed, and tool complain about them.
- Fix …

Run pa11y over open-ui

---

site/src/pages/components/selectmenu.mdx
site/src/pages/prototypes/selectmenu.mdx

The broken links were pointed out here: https://github.com/openui/open-ui/pull/711#issuecomment-1501412028

Remove some broken links in selectmenu explainers

---

site/src/pages/components/accordion.research.mdx
site/src/sources/bootstrap.json
site/src/sources/index.js
site/src/sources/materialUI.json
site/src/sources/tailwind.json

This creates new files for Material UI and for Tailwind Elements, and adds only the Accordion component to them.
It also drops the "Concepts" part of the accordion research page since it only has data from one system and thus isn't very useful.

Add three more accordion components.

---

site/src/pages/components/popover.research.explainer.mdx

Now that the spec has landed and MDN has documentation, link to them.

Add links to WHATWG and MDN to the Popover explainer

---

site/src/pages/components/accordion.explainer.mdx

Sorry I'm not sure how I missed what was actually _in_ 748 when merged, but there is some real confusion there that is probably easier to correct in a PR and a comment.
This PR _removes_ references to the old 2015 proposal which was _also_ called panelset. I'm sorry 😆 
While there are some surface similarities in that what was defined was a general structure on which several views could be laid, they are in almost every practical way very different things and thus most of the content/critique in there is not talking about the actual work this group did. That work was preliminary referred to as "spicy-sections" because: a) it followed hixie's original idea [in the HTML spec of just putting a marker element around some sections](https://whatwg.org/specs/web-apps/2006-01-01/#switch) b) we …

Panelset isn't panelset - update accordion.explainer.mdx

---

site/src/pages/components/popover.research.explainer.mdx

Based on the log at
https://app.netlify.com/sites/open-ui/deploys/648757635e920e0008e01eb0 it seems like this attempt to use webidl syntax highlighting causes the warning (unattributed to any file):
The language "webidl" doesn't exist, falling back to plaintext.
This removes the unneeded language (which doesn't cause any highlighting) and adds a closing brace as well.

Stop trying to use webidl syntax highlighting that doesn't exist.

---

site/package.json
site/yarn.lock

Resolved: https://github.com/openui/open-ui/issues/790
All new installs were failing, and it was due to this problem:
https://github.com/astro-community/astro-compress/issues/163
Looks like the author of `astro-compress` wanted to quit OSS, so deleted their NPM, but didn't transfer ownership, and as a result the package was deleted from the registry. (I didn't know this could happen! 😱)
It has since been transferred and re-released. They'll also migrate the repo over to the official Astro repo soon.
Updating to the latest version of the package resolved this

bugfix: update compress package

---

site/src/components/select-anatomy.jsx
site/src/pages/components/selectlist.mdx

This new anatomy was proposed and agreed on here:
https://github.com/openui/open-ui/issues/702

Use new selectmenu anatomy in explainer

---

site/src/pages/components/popover-hint.research.explainer.mdx

Per the resolution:
- [OpenUI: Resolution to use `interest` as the name of the value](https://github.com/openui/open-ui/issues/767#issuecomment-1654177227)
This also updates the articles and references section to include that, and adds a bit more text explaining the new name.

Rename `hover` to `interest`

---

site/src/pages/components/file.mdx

Previously a reference was made to `click()` but this wasn't defined so I've done that. Also added the definiton of the newer `showPicker()` method.

Add definition for click and showPicker methods to the file editors draft

---

site/src/pages/components/selectlist.mdx

This is being discussed here:
https://github.com/openui/open-ui/issues/808
I renamed it to <selectedoption> for now in the chromium prototype, so the explainer should match.

Rename selectedvalue to selectedoption

---

site/src/components/contributors.astro

Updated the homepage to add the second page of the Open UI contributors on GitHub, as i noticed there are some people in there who are frequently involved with open-ui but not necessarily opening a lot of pull requests.
Screenshot:

Add page 2 of the contributors on the homepage

---

site/README.md

Rename `research` to `site` in `site/README.md`. This was missed from the commit from before.

Rename `research` to `site`

---

site/src/pages/components/invokers.explainer.mdx
site/src/pages/components/popover-hint.research.explainer.mdx
site/src/pages/components/popover.research.explainer.mdx

Explainers now make it clear we intend for `invoketarget` to replace `popovertarget`
Fixes https://github.com/openui/open-ui/issues/869

Update invokers and popover explainers

---

site/src/components/navigation/navigation.astro
site/src/pages/components/accordion.explainer.mdx
site/src/pages/components/breadcrumb.mdx
site/src/pages/components/checkbox.mdx
site/src/pages/components/file.mdx
site/src/pages/components/focusgroup.explainer.mdx
site/src/pages/components/popover-hint.research.explainer.mdx
site/src/pages/components/popover.research.explainer.mdx
site/src/pages/components/selectlist.mdx

This handles an aspect of #801 as I want to do the resolution in chunks as I want the status to be in the front matter so breaking up the PR. This PR lands a new section for Active and Non-active proposals.

Added active and non-active sections, part of issue #801

---

site/src/pages/components/invokers.explainer.mdx

Originally done in https://github.com/keithamus/invoker-buttons-proposal/pull/31
Hi @keithamus , thanks for this proposal! Anything that can make HTML on its own more capable is great!
Quick PR to fix the typo `'togglePopvoer'`

Fix `'togglePopvoer'` typo

---

site/src/layouts/ComponentLayout.astro
site/src/pages/components/selectlist.mdx

The images appear squashed an distorted on mobile currently. This fixes that.
| Before | After |
| ------  | ----- |
| ![image](https://github.com/openui/open-ui/assets/32498324/d2933868-c9d8-4757-98c6-9565417cd359) | ![image](https://github.com/openui/open-ui/assets/32498324/b1f1a002-b00e-43bc-b01e-85d513d9fe76)|

Improve selectlist use case UI on mobile

---

site/src/pages/components/file.mdx

- Remove click() references as `showPicker()` is the intended API for this.
- Add missing 'cancel' event.
- Update Native File System API URL.
References to the label part have been left for now pending discussion in #894

Updates to file proposal

---

site/src/pages/components/popover-hint.research.explainer.mdx

This adds a "Popover Stacks" section that explains the new double-stack algorithm that came out of the discussion at https://github.com/whatwg/html/issues/9776#issuecomment-1834130914. This has already been prototyped in Chromium and it looks like it works fairly well.
@josepharhar

Update popover=hint explainer to include double-stack algorithm

---

site/src/pages/components/interest-invokers.explainer.mdx
site/src/pages/components/invokers.explainer.mdx
site/src/pages/components/popover-hint.research.explainer.mdx

This split the Invokers proposal into 2 separate sections; "Invokers" (what might also be known as `invoketarget`/`invokeaction` and related behaviour) and "Interest Invokers" (what might also be known as `interesttarget`). It also starts to demarcate chunks of the "Invokers" proposal into what we're initially shipping, vs what will come as a follow-up.
(I'm aware this is a big diff but... it's quite a bit to tease these apart, I can try and split it into smaller PRs if people would feel better about that?)
Closes https://github.com/openui/open-ui/issues/964, https://github.com/openui/open-ui/issues/956

split & tidy up the Invokers proposals, scoping for v1 invokers

---

site/src/layouts/Layout.astro

Because of the many nav items we have. I thought it might be nice to have a skip to content link as first tab on the page.
A small accessibility improvement.
Screenshot:

Add skip to content link

---

site/src/pages/components/popover.research.explainer.mdx

This was an oversight in the explainer. The landed spec:
https://html.spec.whatwg.org/multipage/popover.html#popover-light-dismiss
shows the correct behavior.

Remove blur as light dismiss trigger

---

.github/CODEOWNERS

We can update codeowners more as time goes on but as a first attempt I think it makes sense for me and Keith to "own" invokers (including interest) in addition to the 3 main codeowners?

Update code owners for invokers to include Keith and I (Luke)

---

.github/CODEOWNERS

Enable me to edit focusgroup explainer, merge PRs, etc.

Add Travis as owner in CODEOWNERS

---

site/src/pages/components/focusgroup.explainer.mdx

* Adds a use case directionality of arrow keys following content.
* Slightly more precise definition of the directionality values of `inline` and `block`.
* Removes previous values of `horizontal` and `vertical` (which were not recommended values as these are not content-direction aware).
* Replaces usages of `horizontal` and `vertical` with corresponding `inline` and `block` and updates associated prose.
Fixes: #522

[focusgroup] Clarify i18n arrow key directionality mapping

---

site/src/pages/components/focusgroup.explainer.mdx

Re-reading focusgroup explainer: fix broken link

---

site/src/pages/components/invokers.explainer.mdx

Fixes #968
Closes #967 
Definitely needs some thought with regards to aria mappings that perhaps @scottaohara could help with. But think it's a good idea to get these listed as future so we do address them.

Add stepUp and stepDown actions for number inputs

---

site/src/pages/components/selectlist.mdx

Fixes https://github.com/openui/open-ui/issues/863

Add checkmark to select explainer

---

site/src/pages/components/invokers.explainer.mdx

Here's an attempt at rewriting the explainer to use `command`/`commandfor`.
/cc @mfreed7 @lukewarlow

rewrite invokers explainer to use new command/commandfor naming

---

site/src/pages/components/invokers.explainer.mdx

In the example there were two `commandfor` and no `command`.  h/t @alice

Fix a typo in example

---

site/src/pages/components/invokers.explainer.mdx

In #1065 we renamed to use the new `commandfor`/`command` syntax but these few were missed. This PR fixes this.

fix a few missed invoketarget/invokeaction renames

---

site/src/pages/components/selectlist.mdx

Some offline discussions have shown that calling this feature "stylable" select is confusing since there is much more capability than just styling with CSS since you can add a lot of newer HTML content. "Customizable" is a more accurate term.

Rename Stylable Select to Customizable

---

site/src/pages/components/invokers.explainer.mdx

This updates the Invokers explainer to match the current conclusions based on WHATWG discussions.
See https://github.com/whatwg/html/issues/10471 for minutes.
We'll hopefully discuss the heuristics for custom attributes in the next OpenUI meeting, but for now this commits the latest reality of what is being proposed.

use dashes in attribute values, 

---

site/src/pages/components/invokers.explainer.mdx

This updates the invokers explainer to feature the `--` syntax as resolved in https://github.com/openui/open-ui/issues/969#issuecomment-2251551230.
Closes https://github.com/openui/open-ui/issues/969. Refs https://github.com/openui/open-ui/issues/954
It also fixes a few missed conversions of camel-to-dash for built-ins.

[invokers] update custom commands to use -- syntax

---

site/src/pages/components/customizableselect.mdx

Based on discussion and developer feedback in the WHATWG issue about HTML parser changes for <select>, we are not requiring <datalist> to be added to the author HTML for most cases. This PR updates the explainer to remove <datalist> in a bunch of places.
https://github.com/whatwg/html/issues/10310

Update HTML parser changes in select explainer

---

site/src/pages/components/customizableselect.mdx

This patch moves up the section about how to test out the customizable select API and also recommends using chrome canary because I am constantly changing the API.

Move up and improve "testing out" section

---

site/src/pages/components/invokers.explainer.mdx

This rewrites the a11y section on invokers to be far more comprehensive, detailing the exact intentions we have when it comes to applying various ARIA states to the button, as well as focus fixups.

rewrite accessibility section on invokers

---

site/src/pages/components/customizableselect.mdx

Correcting 2 small typos on the Customizable Select page.

Correcting typos in Customizableselect page

---

site/src/schemas/design-system.schema.json

It looks like the `open-ui/site/src/schemas/design-system.schema.json` file has some placeholder data hanging out.
```json
{
"$id": "https://example.com/address.schema.json",
"$schema": "http://json-schema.org/draft-07/schema#",
"description": "An address similar to http://microformats.org/wiki/h-card",
```
I took the description from the definition on the [openui website](https://open-ui.org/design-system-analysis-guide/#whats-a-design-system).

Fixing design-system.schema.json schema placeholder content

---

site/src/sources/spectrum.json

To make it easier to maintain in the future, I generated the JSON using the component options schema from [adobe/spectrum-tokens](https://github.com/adobe/spectrum-tokens).
I think I could further automate more metadata, so this is just a start.

Updated spectrum with full component list

---

site/src/pages/components/customizableselect.mdx

Remove eager selection of select option with arrow keys

---

site/src/pages/components/customizableselect.mdx

Update explainer with button behaviors

---

site/src/pages/components/invokers.explainer.mdx

- Remove left over references to `input[type=button]` as that's not supported.
- Update explanations for type="reset" and type="submit".
- Add explanation for why `input[type=button]` isn't supported.
- Add explicit type="button" to all the example buttons.

Update invokers explainer

---

site/src/pages/components/interest-invokers.explainer.mdx

Remove interestaction from interest invokers

---

.github/CODEOWNERS
site/src/pages/components/press-button.explainer.mdx

Introduce initial Press Button explainer

---

.github/CODEOWNERS
site/src/pages/components/invokers.explainer.mdx
site/src/pages/components/openable.explainer.mdx

Initial draft of an explainer for the proposed openable API see #700 
The plan is to address the remaining chunks of this (such as the big "Why not `<details>`?" question) in follow-ups to make them easier to review. Some of these will need further discussion as a group too.

Add initial explainer for openable API.

---

site/src/components/navigation/navigation.astro
site/src/env.d.ts
site/src/pages/components/accordion.explainer.mdx
site/src/pages/components/future-invokers.explainer.mdx
site/src/pages/components/invokers.explainer.mdx
site/src/pages/components/popover-hint.research.explainer.mdx
site/src/pages/components/popover.research.explainer.mdx

Move Exclusive Accordion, Invoker Commands, Popover APi and Popover=hint to graduated proposals section
Split out future invoker commands to new active proposal
Closes #1151

Add Graduated Proposals section

---

site/src/pages/components/interest-invokers.explainer.mdx

It seems better to use a new value for `interactivity` rather than inventing a new property.

Change from a new keyboard-focusable property to use interactivity

---

site/src/pages/components/focusgroup.explainer.mdx

No one is driving this right now so moving it to the non-active proposals section.
It might be that we're better off focusing attention on proposals such as built-in aria menus, and toolbars. Which would address some of the use cases for this feature.

Move focusgroup to non-active proposals menu

---

site/src/pages/components/menu.explainer.mdx

This PR marks `<menuitemcheckbox>` and `<menuitemradio>` as obsolete additions to the menu elements proposal, in favor of `<fieldset checkable=single|multiple>` wrapping ordinary `<menuitem>` elements. Closes https://github.com/openui/open-ui/issues/1189.
Various other small additions and formatting changes are included in this PR.

"Deprecate" `menuitemcheckbox` & `menuitemradio` from menu elements proposal

---

site/astro.config.js
site/public/styles/prism-dark.css
site/src/layouts/BaseLayout.astro
site/src/pages/components/interest-invokers.explainer.mdx

This fixes WebIDL warnings
Fixes https://github.com/openui/open-ui/issues/693

Switch shiki for prism

---

site/src/pages/components/future-invokers.explainer.mdx
site/src/pages/components/invokers.explainer.mdx

https://html.spec.whatwg.org/multipage/form-elements.html#attr-button-command-request-close-state

Move request-close command to the graduated command list

---

.github/workflows/generate-telecon-agenda.yml

@mfreed7 @gregwhitworth 
This workflow runs every Wednesday at mightnight in order to generate a telecon agenda `.md` file, with the date set to the Thursday following (as in, the next day).
The contents of the markdown file follow the format of prior files - it has a heading with the date of the Thursday that week, followed by a bullet-point list of issues. The issues are listed in numerical order - smallest issue number first - to ensure that older issues get a chance to be handled before others. 
Given this runs on a Wednesday at midnight, the chairs can re-order them at any point before the meeting. The workflow can also be manually re-run to pick up new agenda items, at any point.

add workflow to generate telecon agendas

---

site/public/styles/global.css

The default font size for most browsers is 16px already, but some people (including myself) like to toggle the default font size in the browser settings. Explicitly setting the default font size to 16px in CSS overrides that preference.

Stop explicitly setting font size for website

---

.github/workflows/generate-telecon-agenda.yml

In https://github.com/openui/open-ui/pull/1262 we added a script to generate telecon agendas, but the script pushed the agenda into `main`, which is a protected branch, and so the action fails.
We have a couple of options:
1. Remove branch protection and allow the action to push.
2. Add bypass to the branch protection for GitHub Actions, so it can push but others cannot.
3. Have the action generate a PR each time.
Rather than raise an issue to figure out which choice to make, I thought I'd raise a PR implementing choice 3. I think I'd prefer option 2 if we can make that happen, but in lieu of doing that, this PR should work to generate a PR each time we run the telecon agenda action.
/cc @mfreed @gregwhitworth

Create PRs for Telecon Agenda generation, over pushing to main

---

.github/workflows/generate-telecon-agenda.yml

The telecon agenda generate action was failing because it didn't know what upstream to push to... when I tested this locally it worked, but I have `push.autoSetupRemote` configured which meant `git push` just worked, however CI does not have that.

Fix generate-telecon-agenda.yml push

---

meetings/telecon/2025-09-04.md

Open UI Telecon Agenda, September 04, 2025
===================================
* [command invokers] scroll command [#1220](https://github.com/openui/open-ui/issues/1220)
* Open a11y questions for overflow/carousels [#1265](https://github.com/openui/open-ui/issues/1265)
* Scoped focusgroup explainer [1260](https://github.com/openui/open-ui/pull/1260)

Add Scoped focusgroup explainer to telecon agenda

---

site/src/pages/components/enhanced-range-input.explainer.mdx

Here are some of the changes to the explainer based on telecons / feedback.
The idea is to move this forward and to get more directed author feedback. The next step in this is surely community feedback.
Adopts some semantically correct patterns: `<fieldset>`/`<legend>` pattern. The `<legend>` provides the group's accessible name, while each handle (`<input>`) gets its own dedicated `<label>`.
Implemented the idea where the **"tightest constraint wins."** A handle's movement is clamped by the intersection of its own `min`/`max` and the parent's `min`/`max`.
A new "Track Click Behavior" section has been added, specifying that a click will move the **closest thumb** to that position. This did not go by a telecon yet, but It might be a good first idea, explainer can be updated
The document …

[Range] Add update from meetings and add poc as reference

---

.github/workflows/generate-telecon-agenda.yml

`generate-telecon-agenda` has been failing to make PRs over the last few weeks as it's missing this permission.
With this fix in place it should be able to generate the PRs correctly.

Allow generate-telecon-agenda to generate PRs
